services:
  postgres:
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_DB: fyndo
      POSTGRES_USER: fyndo_user
      POSTGRES_PASSWORD: fyndo_234

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fyndo_user -d fyndo"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: .
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      sh -c "
      npx drizzle-kit push &&
      npx pm2-runtime ecosystem.config.cjs
      "

volumes:
  pgdata:
